{
    "68.96.83.151:60405":{
        "contact":"contact@yk3music.com",
        "ipv6":"fcbb:1db3:54fb:e519:d915:d7db:4893:4f30",
        "organization":"Yk3 Music",
        "password":"98b31ngx6mw2zcd4jwqycrkcp7jnc31",
        "peerName":"yk3music-irvine",
        "publicKey":"kllz76rusmyk3748yz3tgnv9xhtv08nd2nss31fjuwkgwf9hvys0.k"
        "ipfs":"/tcp/4001/ipfs/QmZEiPvrfZHapq4uiyTDEcR2szCUhDnjdS4q3Uv2b1Uh88",
        "ipfs-pub":"CAASpgIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC1eLf3s4itmj7loHGFLkHfxl4nxnVBr3VVqkWDnH2mZzV5zG1AlfwZch+WSFFyyqMCaog/rlPbGsRhBn2xd9zTxfHUdktqAOxKOLGFNNpwT72B9Ah013h7gtEJbDz6p+DqW3OAFc6GyRMyn66ukwj3Xkhtm24RuG0wjrerPo3eQDHHXfdws64xxEO0U5eVeu5vXv6viVgtBhEhmRpPK1cqwKmmk9eIAFPQfc1nNMABaZXiMQCD9QTPP47IJZM69+XQzzHXBcyeHMiZvHPzqcKET4E82gRF6CuhKB0nGfiyWKvxlqO3Z37Jv6sWnkEO7g/AhfTEwxlUzNVU5gao2+s7AgMBAAE="
    }
}
