{
    ":60405":{
        "contact":"contact@yk3music.com",
        "ipv6":"fcbb:1db3:54fb:e519:d915:d7db:4893:4f30",
        "organization":"Yk3 Music",
        "password":"98b31ngx6mw2zcd4jwqycrkcp7jnc31",
        "peerName":"yk3music-irvine",
        "publicKey":"kllz76rusmyk3748yz3tgnv9xhtv08nd2nss31fjuwkgwf9hvys0.k",
        "ipfs":"/tcp/4001/ipfs/QmZEiPvrfZHapq4uiyTDEcR2szCUhDnjdS4q3Uv2b1Uh88"
    }
}
