"leeloo.kyriasis.com:65149": {
    "login": "public-peer",
    "password": "3fPUWtOiQfKRupM7y9zIAdZhbLiaumoCutVJx9Igw/bZerEhbOfDdEFxJZojcnw0jMcOR/dZvFElmqI6",
    "publicKey": "4dhktl7cmwp0f1grjuhn1m5gg3tllx1mccssmgq2s6xqltzpu620.k",
    "ipv6": "fcb9:72d4:cd1b:57f4:1ab0:bd4:e015:7e03",
    "contact": "johannes@kyriasis.com",
    "gpg": "5134 EF9E AF65 F95B 6BB1  608E 50FB 9B27 3A9D 0BB5",
    "peerName": "leeloo.kyriasis.com"
}
