{
    "[2001:67c:2990:f00::9ef0:3eaf]:31545":{
        "contact":"hostmaster@cwningen.cymru",
        "gpg":"2FCD 352C E105 73B5 E753  6B98 36C9 9B69 B60E 86E6",
        "gpg-public-key":"https://cwningen.cymru/gpg.pub",
        "login":"public-peer",
        "password":"hsfmhcphy3dpfy6f15hgyz30206dmry",
        "peerName":"pen.cwningen.cymru",
        "publicKey":"hp3mrxspcg2p2nzt9885gmb9wcgm4t1huc2dydk6hqh63u44nrg0.k"
    }
}
