{
    "163.172.26.210:27410":{
        "login":"public-peer",
        "password":"ZGZWKOX5H535MG7MRYRKFMF4IY5GFCO5",
        "peerName":"h.totem.tfnux.org",
        "publicKey":"8bqv77rkzn888mcr8wu3k9b22hpczhn7c0zzyrqpj4bbx8rbf810.k"
    },

    "[2001:bc8:2495:100::1]:27410":{
        "login":"public-peer",
        "password":"ZGZWKOX5H535MG7MRYRKFMF4IY5GFCO5",
        "peerName":"h.totem.tfnux.org",
        "publicKey":"8bqv77rkzn888mcr8wu3k9b22hpczhn7c0zzyrqpj4bbx8rbf810.k"
    }
}

